spring.application.name=teste_tecnico
spring.datasource.url=jdbc:mysql://localhost:3306/revex
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=4000
spring.web.error.include-message=always